export enum TypeImage {
    AVATAR='AVATAR',
    PRODUCT='PRODUCT',
    CATEGORY_PRODUCT='CATEGORY_PRODUCT',
    AVATAR_SHOP='AVATAR_SHOP',
    BACKGROUND_SHOP='BACKGROUND_SHOP',
    CATEGORY='CATEGORY',
    SHOP='SHOP',
    TOPPING='TOPPING',
    DOCS='DOCS'
}
